[package]
name = "egui_wgpu"
version = "0.1.0"
authors = ["John Michael Bell <johnmichaelbell@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dev-dependencies]
egui = { version = "0.1", features = ["serde"] }
egui_glium = "0.1"
serde = { version = "1", features = ["derive"] }